---
services:
  vue-app:
    build:
      context: ./app
      dockerfile: ${BANDCAL_DOCKERFILE_VUE:-Dockerfile}
      args:
        VITE_APP_TITLE: ${VITE_APP_TITLE:-Bandcal}
        VITE_APP_COLOR_SCHEME: ${VITE_APP_COLOR_SCHEME:-default}
        VITE_BASE_PATH: ${VITE_BASE_PATH}
        VITE_API_BASE_PATH: ${VITE_API_BASE_PATH:-/api}
        VITE_PORT: ${VITE_PORT:-8081}
    container_name: vue-app${BANDCAL_POSTFIX}
    env_file:
      - ./.env
    restart: always
    networks:
      - bandcal-network
    volumes:
      - ./app:/app

  api:
    build:
      context: ./api
      dockerfile: ${BANDCAL_DOCKERFILE_API:-Dockerfile}
    container_name: api${BANDCAL_POSTFIX}
    env_file:
      - ./.env
    restart: always
    networks:
      - bandcal-network
    volumes:
      - ./api:/app
      - ./db:/db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx${BANDCAL_POSTFIX}
    env_file:
      - ./.env
    ports:
      - "${BANDCAL_PORT:-8080}:${BANDCAL_PORT:-8080}" # Ensure Nginx serves everything under localhost:8080
    volumes:
      - ./nginx/start-nginx.sh:/start-nginx.sh:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - vue-app
      - api
    networks:
      - bandcal-network

networks:
  bandcal-network:
    name: bandcal-network${BANDCAL_POSTFIX} # Dynamically set the name
    driver: bridge
