---
services:
  vue-app:
    build:
      context: ./app
      dockerfile: ${BANDCAL_DOCKERFILE_VUE:-Dockerfile}
    container_name: vue-app${BANDCAL_POSTFIX}
    restart: always
    networks:
      - bandcal-network
    volumes:
      - ./app:/app
    environment:
      - VUE_APP_BASE_URL=${VUE_APP_BASE_URL} # Pass VUE_APP_BASE_URL to the container

  api:
    build:
      context: ./api
      dockerfile: ${BANDCAL_DOCKERFILE_API:-Dockerfile}
    container_name: api${BANDCAL_POSTFIX}
    restart: always
    networks:
      - bandcal-network
    volumes:
      - ./api:/app
      - ./db:/db
      - ./api/config/config.json:/app/config/config.json:ro

  nginx:
    image: nginx:latest
    container_name: nginx${BANDCAL_POSTFIX}
    ports:
      - "${BANDCAL_PORT:-8080}:8080" # Ensure Nginx serves everything under localhost:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - vue-app
      - api
    networks:
      - bandcal-network

networks:
  bandcal-network:
    name: bandcal-network${BANDCAL_POSTFIX} # Dynamically set the name
    driver: bridge
