---
services:
  vue-app:
    build:
      context: ./app
      dockerfile: ${BANDCAL_DOCKERFILE_VUE:-Dockerfile}
    container_name: vue-app${BANDCAL_POSTFIX}
    env_file:
      - ./.env
    restart: always
    networks:
      - bandcal-network
    volumes:
      - ./app:/app

  api:
    build:
      context: ./api
      dockerfile: ${BANDCAL_DOCKERFILE_API:-Dockerfile}
    container_name: api${BANDCAL_POSTFIX}
    env_file:
      - ./.env
    restart: always
    networks:
      - bandcal-network
    volumes:
      - ./api:/app
      - ./db:/db
      - ./api/config/config.json:/app/config/config.json:ro

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx${BANDCAL_POSTFIX}
    env_file:
      - ./.env
    # environment:
    #   - BANDCAL_PORT=${BANDCAL_PORT:-8080}
    #   - VITE_BASE_PATH=${VITE_BASE_PATH:-/}
    ports:
      - "${BANDCAL_PORT:-8080}:${BANDCAL_PORT:-8080}" # Ensure Nginx serves everything under localhost:8080
    volumes:
      # - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - vue-app
      - api
    networks:
      - bandcal-network

networks:
  bandcal-network:
    name: bandcal-network${BANDCAL_POSTFIX} # Dynamically set the name
    driver: bridge
