---
services:
  vue-app:
    build:
      context: ./app
      dockerfile: ${DOCKERFILE_VUE:-Dockerfile}
    container_name: vue-app
    restart: always
    ports:
      - "8081:8081" # Map the Vue app service port correctly
    volumes:
      - ./app:/app

  api:
    build:
      context: ./api
      dockerfile: ${DOCKERFILE_API:-Dockerfile}
    container_name: api
    restart: always
    ports:
      - "3000:3000" # Map the API service port correctly
    volumes:
      - ./api:/app
      - ./db:/db
      - ./api/config/config.json:/app/config/config.json:ro

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080" # Ensure Nginx serves everything under localhost:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - vue-app
      - api
